# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_suspendable}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Josh Kalderimis}]
  s.date = %q{2011-06-09}
  s.description = %q{Has a user left the organisation? Or maybe the account created was bogus? Remove access for a user with a click of a button}
  s.email = %q{josh.kalderimis@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/devise_suspendable.rb",
    "lib/devise_suspendable/model.rb",
    "lib/devise_suspendable/schema.rb",
    "rails/init.rb",
    "test/devise_suspendable_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshk/devise_suspendable}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.3}
  s.summary = %q{Devise user account suspension module}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["> 3.0.4"])
      s.add_runtime_dependency(%q<devise>, [">= 1.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.4"])
      s.add_dependency(%q<devise>, [">= 1.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.4"])
    s.add_dependency(%q<devise>, [">= 1.3"])
  end
end

